// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginResponse struct {
	JwtToken string `json:"jwtToken"`
	User     *User  `json:"user"`
}

type NewUser struct {
	FullName string `json:"fullName"`
	Email    string `json:"email"`
	Country  string `json:"country"`
	Password string `json:"password"`
}

type Pagination struct {
	AfterID *string `json:"afterId"`
	Limit   int     `json:"limit"`
}

type User struct {
	ID       string `json:"id"`
	FullName string `json:"fullName"`
	Email    string `json:"email"`
	Country  string `json:"country"`
}
