// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CartItem struct {
	ID         string   `json:"id"`
	ProductSku string   `json:"productSku"`
	Product    *Product `json:"product"`
	Quantity   int      `json:"quantity"`
}

type LoginResponse struct {
	JwtToken string `json:"jwtToken"`
	User     *User  `json:"user"`
}

type NewCartItem struct {
	ProductSku string `json:"productSku"`
	Quantity   int    `json:"quantity"`
}

type NewProduct struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Category    string  `json:"category"`
	Brand       *string `json:"brand"`
	Price       float64 `json:"price"`
	ImageURL    string  `json:"imageUrl"`
}

type NewUser struct {
	FullName string `json:"fullName"`
	Email    string `json:"email"`
	Country  string `json:"country"`
	Password string `json:"password"`
}

type Pagination struct {
	AfterID *string `json:"afterId"`
	Limit   int     `json:"limit"`
}

type Product struct {
	Sku         string  `json:"sku"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Category    string  `json:"category"`
	Brand       string  `json:"brand"`
	Price       float64 `json:"price"`
	ImageURL    string  `json:"imageUrl"`
}

type User struct {
	ID       string `json:"id"`
	FullName string `json:"fullName"`
	Email    string `json:"email"`
	Country  string `json:"country"`
}
